version: '3'

services:
  nest:
    build: .
    container_name: lion-nest
    networks:
      - lion-network
    tty: true
    volumes:
      - .:/node
    ports:
      - "3333:3333"

  postgres:
    image: postgres:alpine
    container_name: lion-postgress
    tty: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=lion
    networks:
      - lion-network

  adminer:
    image: adminer
    container_name: lion-adminer
    tty: true
    ports:
      - 8080:8080
    networks:
      - lion-network

networks:
  lion-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
